name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_BUNGIE_REDIRECT_URI: ${{ secrets.REACT_APP_BUNGIE_REDIRECT_URI }}
        REACT_APP_BUNGIE_CLIENT_ID: ${{ secrets.REACT_APP_BUNGIE_CLIENT_ID }}
        REACT_APP_BUNGIE_CLIENT_SECRET: ${{ secrets.REACT_APP_BUNGIE_CLIENT_SECRET }}
        REACT_APP_BUNGIE_API_KEY: ${{ secrets.REACT_APP_BUNGIE_API_KEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: build